-- Migration: seed the graph from the hand-authored CSVs
-- Author: ../prs_diags/scripts/graph_seed_export.py -- GENERATED, do not edit by hand
-- Phase: 1-2 (see §8 of design/graph-network-design.md)
--
-- Regenerate with:
--   ./venv/bin/python ../prs_diags/scripts/graph_seed_export.py \
--       design/graph-seed-v1.csv \
--       design/graph-water-v1.csv \
--       -o migrations/<this file>
--
-- Source: graph-seed-v1.csv, graph-water-v1.csv
-- 176 nodes, 231 edges (ELECTRICITY 192, WATER 39), 98 node-attached and 6 edge-attached measurements
--
-- Idempotent: re-running upserts nodes, and leaves existing edges and
-- measurements untouched. It never deletes; retiring a node or a feed is
-- a deliberate UPDATE ... SET is_active = FALSE, not a side effect of a reseed.

BEGIN;

-- ----------------------------------------------------------------------
-- Nodes (176)
-- ----------------------------------------------------------------------
INSERT INTO graph.node
    (tenant_id, node_code, node_name, node_class, is_passthrough, attrs,
     effective_from, effective_to)
VALUES
    (3, 'AHU_10_11', 'AHU 10-11', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'AHU_12_13', 'AHU 12-13', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'AHU_14', 'AHU 14', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'AHU_2_3', 'AHU_2_3', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'AHU_4_7', 'AHU_4_7', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'AHU_LINE1', 'AHU Line 1', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'AHU_LINE2', 'AHU Line 2', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'AHU_LINE3', 'AHU Line 3', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'AIR_DRYER', 'Air Dryer', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'AJL1', 'AJL1', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'AJL2', 'AJL2', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'BOILER_MIURA', 'Boiler Miura', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'CELUP_1A', 'Celup 1A', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'CELUP_1B', 'Celup 1B', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'CELUP_2', 'Celup 2', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'CELUP_3', 'Celup 3', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMPRESSOR_CUCUK', 'Compressor CUCUK', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_100HP', 'Comp 100HP', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_300HP', 'Compressor 300 HP', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_400HP', 'Compressor 400 HP', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_AIKI', 'Comp Aiki', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_ELITE', 'Comp Elite Air', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_FS_INT_1', 'Comp FS Interlace 100HP - 1', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_FS_INT_2', 'Comp FS Interlace 150HP - 2', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_FS_INT_4', 'Comp FS Interlace 150HP - 4', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_FS_WIND_1', 'Comp FS Winder 100HP - 1', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_FS_WIND_2', 'Comp FS Winder 100HP - 2', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_FS_WIND_4', 'Comp FS Winder 150HP - 4', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_FUSHENG300HP', 'Comp Fusheng 300HP', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_INTERLACE', 'Comp Interlace', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_KAESER', 'Comp Kaeser', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_NVX_INT_3', 'Comp NVX 90 Interlace 3', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_NVX_WND_3', 'Comp NVX 160 Winder - 3', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_SCR2200', 'Comp SCR2200', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COMP_WINDER', 'Comp Winder', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COM_SCR_WIND_5', 'Comp SCR 100DW Winder 5', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COOLING1', 'Cooling Tower A2', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'COOLING2', 'Cooling Tower A4', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'DRYER_INT_1', 'Dryer Interlace 1, 2, 3', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'FACTORY_AB', 'Incoming Factory A&B', 'BUS', FALSE, '{"voltage_level":"400V"}'::jsonb, '-infinity'::date, NULL),
    (3, 'FINISHING_1', 'Finishing 1', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'FINISHING_21', 'Finishing 2.1', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'FINISHING_22', 'Finishing 2.2', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'FLR_124', 'Work Panel Fl. 1, 2, 4', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'GARUK', 'GARUK', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'GAS_ENGINE', 'Gas Engine', 'SOURCE', FALSE, '{"fuel":"NATURAL_GAS"}'::jsonb, '-infinity'::date, NULL),
    (3, 'HEATER_1', 'Heater MC 1', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'HEATER_10', 'Heater MC 10', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'HEATER_11', 'Heater MC11', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'HEATER_2', 'Heater MC 2', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'HEATER_3', 'Heater MC 3', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'HEATER_4', 'Heater MC 4', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'HEATER_5', 'Heater MC 5', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'HEATER_6', 'Heater MC 6', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'HEATER_7', 'Heater MC 7', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'HEATER_8', 'Heater MC 8', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'HEATER_TOTAL', 'Heater Total', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'HVAC_AHU', 'HVAC AHU 1 & 2', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'HVAC_CHILLER1', 'HVAC Chiller 1', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'HVAC_CHILLER2', 'HVAC Chiller 2', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'INCOMING_PLN', 'Incoming PLN 1', 'SOURCE', FALSE, '{"voltage_level":"20kV"}'::jsonb, '-infinity'::date, NULL),
    (3, 'KAESER_1', 'Comp Kaeser-1', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'KAESER_2', 'Comp Kaeser-2', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'KAESER_3', 'Comp Kaeser-3', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'KAESER_4', 'Comp Kaeser-4', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LABKNIT', 'Lab Knitting', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LAB_DEVICE', 'Laboratorium', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LIGHTING_MAIN', 'Lighting Main', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LIGHT_INT_1', 'Lighting at Interlace - 1', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LIGHT_INT_2', 'Lighting at Interlace - 2', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVMDB_A1', 'LVMDB A1', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVMDB_A2', 'LVMDB A2', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVMDB_A3', 'LVMDB_A3', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVMDB_A4', 'LVMDB_A4', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVMDB_A5', 'LVMDB A5', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVMDB_B2', 'LVMDB B2', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVMDB_TEXTURE', 'LVMDB Texture TF 1600kVA', 'BUS', FALSE, '{"rated_kva":1600}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVMDB_TEXTURE_2', 'LVMDB Texture TF 2000kVA', 'BUS', FALSE, '{"rated_kva":2000}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVMDB_TF630', 'LVMDB TF 630kVA', 'BUS', FALSE, '{"rated_kva":630}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVMDP_SPINNING_1', 'LVMDP Spinning 1', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVMDP_SPINNING_2', 'LVMDP Spinning 2', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVMDP_SPINNING_3', 'LVMDP Spinning 3', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVSDP_COMP_23', 'LVSDP Compressor 2 & 3', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVSDP_PROD_ATY', 'LVSDP Produksi ATY', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVSDP_SP2_1', 'LVSDP 1', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'LVSDP_SP2_2', 'LVSDP 2', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC302_1_8', 'MC302(1-8)', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC302_9_22', 'MC302(9-22)', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC302_BARU', 'MC302 Baru', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC303_1_9', 'MC303(1-9)', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC303_BARU', 'MC303 Baru', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_ATY', 'MC ATY', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_MOTOR_1', 'MC 1', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_MOTOR_10', 'MC 10', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_MOTOR_11', 'MC 11', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_MOTOR_12', 'MC 12', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_MOTOR_13', 'MC 13', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_MOTOR_2', 'MC 2', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_MOTOR_3', 'MC 3', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_MOTOR_4', 'MC 4', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_MOTOR_5', 'MC 5', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_MOTOR_6', 'MC 6', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_MOTOR_7', 'MC 7', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_MOTOR_8', 'MC 8', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_MOTOR_9', 'MC 9', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_SP_A', 'MC SP Line A', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_SP_B', 'MC SP Line B', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_SP_C', 'MC SP Line C', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_SP_D', 'MC SP Line D', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_SP_E', 'MC SP Line E', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_SP_F', 'MC SP Line F', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_SP_G', 'MC SP Line G', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_SP_H', 'MC SP Line H', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_SP_I', 'MC SP Line I', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_SP_J', 'MC SP Line J', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'MC_TWIST', 'MC Twisting', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'OFFICE', 'Office RND', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'OFFICE_2', 'Office TF630kv', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'PACKING_DEVICE', 'Packing', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'PKN_DEVICE', 'PKN', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'PLTS_A', 'PLTS A', 'SOURCE', FALSE, '{"type":"PV"}'::jsonb, '-infinity'::date, NULL),
    (3, 'PLTS_A4', 'PLTS A4', 'SOURCE', FALSE, '{"type":"PV"}'::jsonb, '-infinity'::date, NULL),
    (3, 'PLTS_B', 'PLTS B', 'SOURCE', FALSE, '{"type":"PV"}'::jsonb, '-infinity'::date, NULL),
    (3, 'PLTS_TEXTURE', 'PLTS Texture', 'SOURCE', FALSE, '{"type":"PV"}'::jsonb, '-infinity'::date, NULL),
    (3, 'PUMP_COOL_WND', 'Pump Exhaust Fan Cooling Tower Winder', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'RAINCOAT_DEVICE', 'Raincoat', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'REWINDING_DEVICE', 'Rewinding', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'SIPPA', 'SIPPA', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'SIZING', 'Sizing', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'TRICOT', 'Tricot', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'TRICOT1', 'MC Tricoat 1', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'TRICOT2', 'MC Tricoat 2', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WARPING', 'Warping', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WJL1', 'WJL1', 'BUS', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WJL2', 'WJL2', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WJL3', 'WJL3', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WJL4', 'WJL4', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WORKSHOP', 'Workshop', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_ATY', 'WTP-1 ATY', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_BIO', 'WTP-1 Tandon Biologis', 'STORAGE', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_CLR', 'WTP-1 Clarifier', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_IN_1', 'WTP-1 Intake 1', 'SOURCE', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_IN_2', 'WTP-1 Intake 2', 'SOURCE', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_IPAL', 'WTP-1 IPAL', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_OVR', 'WTP-1 Overflow TBio', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_RAN', 'WTP-1 Tandon Air Hujan', 'SOURCE', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_RAW', 'WTP-1 Raw Water', 'STORAGE', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_REUSE', 'WTP-1 Reuse to TRain', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_SOFT', 'WTP-1 Soft Water Tank', 'STORAGE', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_SOFT_1', 'WTP-1 Softener 1', 'CONVERSION', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_SOFT_2', 'WTP-1 Softener 2', 'CONVERSION', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_SPN', 'WTP-1 Spinning', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_WJL_REC', 'WTP-1 Recycle WJL', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP1_WVN', 'WTP-1 Weaving', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_BEAM', 'WTP-2 Beam Process', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_CLR', 'WTP-2 Clarifier', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_DEL', 'WTP-2 Delivery Tank', 'STORAGE', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_EQL', 'WTP-2 Equalized Tank', 'STORAGE', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_HW_1', 'WTP-2 Hot Water Tank 1', 'STORAGE', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_HW_2', 'WTP-2 Hot Water Tank 2', 'STORAGE', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_IN_1', 'WTP-2 Intake 1', 'SOURCE', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_IN_2', 'WTP-2 Intake 2', 'SOURCE', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_IPAL', 'WTP-2 IPAL', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_PROC', 'WTP-2 Processing', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_RAW', 'WTP-2 Raw Water', 'STORAGE', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_REACT', 'WTP-2 Reaction Tank', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_RO_PROC', 'WTP-2 RO Process', 'CONVERSION', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_RO_TANK', 'WTP-2 RO Tank', 'STORAGE', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_RPD', 'WTP-2 Rapid Process', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_SOFT', 'WTP-2 Soft Water Tank', 'STORAGE', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_SOFT_3', 'WTP-2 Softener 3', 'CONVERSION', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_SOFT_4', 'WTP-2 Softener 4', 'CONVERSION', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP2_SOFT_5', 'WTP-2 Softener 5', 'CONVERSION', TRUE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP_1', 'WTP 1', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WTP_2', 'WTP 2', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL),
    (3, 'WWTP', 'WWTP', 'LOAD', FALSE, '{}'::jsonb, '-infinity'::date, NULL)
ON CONFLICT ON CONSTRAINT uq_node_tenant_code DO UPDATE SET
    node_name      = EXCLUDED.node_name,
    node_class     = EXCLUDED.node_class,
    is_passthrough = EXCLUDED.is_passthrough,
    attrs          = EXCLUDED.attrs,
    effective_from = EXCLUDED.effective_from,
    effective_to   = EXCLUDED.effective_to,
    updated_at     = NOW();

-- ----------------------------------------------------------------------
-- Edges (231) -- node ids resolved by code, so this file
-- carries no surrogate keys and can be replayed on any database.
-- ----------------------------------------------------------------------
INSERT INTO graph.edge
    (tenant_id, from_node_id, to_node_id, utility_code, edge_class,
     effective_from, effective_to)
SELECT v.tenant_id, f.id, t.id, v.utility_code, v.edge_class,
       v.effective_from, v.effective_to
FROM (VALUES
    (3, 'AJL2', 'AHU_10_11', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_INTERLACE', 'COMP_FS_INT_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_INTERLACE', 'COMP_FS_INT_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_INTERLACE', 'COMP_FS_INT_4', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_INTERLACE', 'COMP_FS_WIND_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_INTERLACE', 'COMP_FS_WIND_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_INTERLACE', 'COMP_NVX_INT_3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_INTERLACE', 'LIGHT_INT_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_INTERLACE', 'LIGHT_INT_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_KAESER', 'KAESER_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_KAESER', 'KAESER_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_KAESER', 'KAESER_3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_KAESER', 'KAESER_4', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_WINDER', 'COMP_FS_WIND_4', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_WINDER', 'COMP_NVX_WND_3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_WINDER', 'COM_SCR_WIND_5', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_WINDER', 'DRYER_INT_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'COMP_WINDER', 'PUMP_COOL_WND', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'FACTORY_AB', 'LVMDB_A1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'FACTORY_AB', 'LVMDB_A2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'FACTORY_AB', 'LVMDB_A3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'FACTORY_AB', 'LVMDB_A4', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'FACTORY_AB', 'LVMDB_A5', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'FACTORY_AB', 'LVMDB_B2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'FINISHING_22', 'GARUK', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'FINISHING_22', 'SIPPA', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'FINISHING_22', 'WWTP', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'GAS_ENGINE', 'LVMDB_A1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'GAS_ENGINE', 'LVMDB_A2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'GAS_ENGINE', 'LVMDB_A3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'HEATER_TOTAL', 'HEATER_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'HEATER_TOTAL', 'HEATER_10', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'HEATER_TOTAL', 'HEATER_11', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'HEATER_TOTAL', 'HEATER_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'HEATER_TOTAL', 'HEATER_3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'HEATER_TOTAL', 'HEATER_4', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'HEATER_TOTAL', 'HEATER_5', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'HEATER_TOTAL', 'HEATER_6', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'HEATER_TOTAL', 'HEATER_7', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'HEATER_TOTAL', 'HEATER_8', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'INCOMING_PLN', 'FACTORY_AB', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'INCOMING_PLN', 'LVMDB_TEXTURE', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'INCOMING_PLN', 'LVMDB_TEXTURE_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'INCOMING_PLN', 'LVMDB_TF630', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'INCOMING_PLN', 'LVMDP_SPINNING_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'INCOMING_PLN', 'LVMDP_SPINNING_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'INCOMING_PLN', 'LVMDP_SPINNING_3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A1', 'PKN_DEVICE', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A1', 'WJL1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A1', 'WJL2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A1', 'WJL3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A1', 'WJL4', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A2', 'AJL1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A2', 'AJL2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A2', 'COMPRESSOR_CUCUK', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A2', 'COOLING1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A2', 'OFFICE', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A2', 'SIZING', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A2', 'TRICOT', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A2', 'WARPING', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A4', 'COMP_SCR2200', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A4', 'COOLING2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A4', 'WORKSHOP', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A5', 'AIR_DRYER', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A5', 'COMP_300HP', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_A5', 'COMP_400HP', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_B2', 'BOILER_MIURA', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_B2', 'CELUP_1A', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_B2', 'CELUP_1B', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_B2', 'CELUP_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_B2', 'CELUP_3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_B2', 'COMP_100HP', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_B2', 'FINISHING_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_B2', 'FINISHING_21', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_B2', 'FINISHING_22', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_B2', 'LAB_DEVICE', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_B2', 'PACKING_DEVICE', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_B2', 'RAINCOAT_DEVICE', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_B2', 'WTP_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'COMP_ELITE', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'COMP_FUSHENG300HP', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'HEATER_TOTAL', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'HVAC_AHU', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'LABKNIT', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'MC_MOTOR_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'MC_MOTOR_10', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'MC_MOTOR_11', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'MC_MOTOR_12', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'MC_MOTOR_13', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'MC_MOTOR_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'MC_MOTOR_3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'MC_MOTOR_4', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'MC_MOTOR_5', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'MC_MOTOR_6', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'MC_MOTOR_7', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'MC_MOTOR_8', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE', 'MC_MOTOR_9', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'COMP_ELITE', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'COMP_FUSHENG300HP', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'HEATER_TOTAL', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'HVAC_AHU', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'LABKNIT', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'MC_MOTOR_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'MC_MOTOR_10', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'MC_MOTOR_11', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'MC_MOTOR_12', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'MC_MOTOR_13', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'MC_MOTOR_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'MC_MOTOR_3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'MC_MOTOR_4', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'MC_MOTOR_5', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'MC_MOTOR_6', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'MC_MOTOR_7', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'MC_MOTOR_8', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TEXTURE_2', 'MC_MOTOR_9', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TF630', 'LIGHTING_MAIN', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TF630', 'MC302_1_8', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TF630', 'MC302_9_22', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TF630', 'MC302_BARU', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TF630', 'MC303_1_9', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TF630', 'MC303_BARU', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TF630', 'MC_TWIST', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TF630', 'OFFICE_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TF630', 'REWINDING_DEVICE', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDB_TF630', 'WTP_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDP_SPINNING_1', 'COMP_KAESER', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDP_SPINNING_1', 'FLR_124', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDP_SPINNING_1', 'HVAC_CHILLER1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDP_SPINNING_1', 'HVAC_CHILLER2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDP_SPINNING_1', 'MC_ATY', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDP_SPINNING_2', 'LVSDP_SP2_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDP_SPINNING_2', 'LVSDP_SP2_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDP_SPINNING_3', 'AHU_LINE3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDP_SPINNING_3', 'COMP_WINDER', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDP_SPINNING_3', 'LVSDP_COMP_23', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVMDP_SPINNING_3', 'LVSDP_PROD_ATY', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVSDP_COMP_23', 'COMP_INTERLACE', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVSDP_PROD_ATY', 'COMP_AIKI', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVSDP_SP2_1', 'MC_SP_B', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVSDP_SP2_1', 'MC_SP_C', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVSDP_SP2_1', 'MC_SP_D', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVSDP_SP2_1', 'MC_SP_H', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVSDP_SP2_1', 'MC_SP_I', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVSDP_SP2_1', 'MC_SP_J', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVSDP_SP2_2', 'AHU_LINE1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVSDP_SP2_2', 'AHU_LINE2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVSDP_SP2_2', 'MC_SP_A', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVSDP_SP2_2', 'MC_SP_E', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVSDP_SP2_2', 'MC_SP_F', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'LVSDP_SP2_2', 'MC_SP_G', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_A', 'AIR_DRYER', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_A', 'COMP_300HP', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_A', 'COMP_400HP', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_A4', 'COOLING2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_A4', 'WORKSHOP', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_B', 'BOILER_MIURA', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_B', 'CELUP_1A', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_B', 'CELUP_1B', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_B', 'CELUP_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_B', 'CELUP_3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_B', 'COMP_100HP', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_B', 'FINISHING_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_B', 'FINISHING_21', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_B', 'FINISHING_22', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_B', 'LAB_DEVICE', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_B', 'PACKING_DEVICE', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_B', 'RAINCOAT_DEVICE', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_B', 'WTP_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'COMP_ELITE', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'COMP_FUSHENG300HP', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'HEATER_TOTAL', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'HVAC_AHU', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'LABKNIT', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'MC_MOTOR_1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'MC_MOTOR_10', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'MC_MOTOR_11', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'MC_MOTOR_12', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'MC_MOTOR_13', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'MC_MOTOR_2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'MC_MOTOR_3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'MC_MOTOR_4', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'MC_MOTOR_5', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'MC_MOTOR_6', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'MC_MOTOR_7', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'MC_MOTOR_8', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'PLTS_TEXTURE', 'MC_MOTOR_9', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'TRICOT', 'AHU_14', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'TRICOT', 'TRICOT1', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'TRICOT', 'TRICOT2', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'WARPING', 'AHU_12_13', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'WJL1', 'AHU_4_7', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'WJL3', 'AHU_2_3', 'ELECTRICITY', 'FEEDER', '-infinity'::date, NULL::date),
    (3, 'WTP1_ATY', 'WTP1_BIO', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_BIO', 'WTP1_IPAL', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_BIO', 'WTP1_OVR', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_BIO', 'WTP1_REUSE', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_CLR', 'WTP1_SOFT_1', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_CLR', 'WTP1_SOFT_2', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_IN_1', 'WTP1_RAW', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_IN_2', 'WTP1_RAW', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_RAN', 'WTP1_RAW', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_RAW', 'WTP1_CLR', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_SOFT', 'WTP1_ATY', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_SOFT', 'WTP1_SPN', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_SOFT', 'WTP1_WVN', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_SOFT_1', 'WTP1_SOFT', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_SOFT_2', 'WTP1_SOFT', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_SPN', 'WTP1_BIO', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP1_WVN', 'WTP1_WJL_REC', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_BEAM', 'WTP2_EQL', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_CLR', 'WTP2_SOFT_3', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_CLR', 'WTP2_SOFT_4', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_CLR', 'WTP2_SOFT_5', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_DEL', 'WTP2_IPAL', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_EQL', 'WTP2_REACT', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_HW_1', 'WTP2_BEAM', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_HW_1', 'WTP2_HW_2', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_HW_2', 'WTP2_RPD', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_IN_1', 'WTP2_RAW', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_IN_2', 'WTP2_RAW', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_PROC', 'WTP2_HW_1', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_RAW', 'WTP2_CLR', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_REACT', 'WTP2_DEL', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_RO_PROC', 'BOILER_MIURA', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_RO_TANK', 'WTP2_RO_PROC', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_RPD', 'WTP2_EQL', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_SOFT', 'WTP2_PROC', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_SOFT', 'WTP2_RO_TANK', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_SOFT_3', 'WTP2_SOFT', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_SOFT_4', 'WTP2_SOFT', 'WATER', 'PIPE', '-infinity'::date, NULL::date),
    (3, 'WTP2_SOFT_5', 'WTP2_SOFT', 'WATER', 'PIPE', '-infinity'::date, NULL::date)
) AS v (tenant_id, from_code, to_code, utility_code, edge_class,
        effective_from, effective_to)
JOIN graph.node f ON f.tenant_id = v.tenant_id AND f.node_code = v.from_code
JOIN graph.node t ON t.tenant_id = v.tenant_id AND t.node_code = v.to_code
ON CONFLICT ON CONSTRAINT uq_edge DO NOTHING;

-- ----------------------------------------------------------------------
-- Node-attached measurements (98 device/node pairs)
--
-- One row per (target, device, quantity). Quantities come from
-- graph.quantity_rule for that utility, so the set stays in step with the
-- rule table instead of being frozen into this file. A device that does not
-- report a given register simply returns nothing from graph.device_totals.
-- ----------------------------------------------------------------------
INSERT INTO graph.measurement
    (tenant_id, node_id, device_id, quantity_id, utility_code, multiplier, role)
SELECT v.tenant_id, n.id, v.device_id, qr.quantity_id, v.utility_code,
       v.multiplier, 'TOTAL'
FROM (VALUES
    (3, 'AHU_LINE1', 88, 1.0, 'ELECTRICITY'),
    (3, 'AHU_LINE2', 89, 1.0, 'ELECTRICITY'),
    (3, 'AHU_LINE3', 140, 1.0, 'ELECTRICITY'),
    (3, 'AIR_DRYER', 136, 1.0, 'ELECTRICITY'),
    (3, 'AJL1', 30, 1.0, 'ELECTRICITY'),
    (3, 'AJL2', 29, 1.0, 'ELECTRICITY'),
    (3, 'BOILER_MIURA', 8, 1.0, 'ELECTRICITY'),
    (3, 'CELUP_1A', 14, 1.0, 'ELECTRICITY'),
    (3, 'CELUP_1B', 13, 1.0, 'ELECTRICITY'),
    (3, 'CELUP_2', 15, 1.0, 'ELECTRICITY'),
    (3, 'CELUP_3', 7, 1.0, 'ELECTRICITY'),
    (3, 'COMPRESSOR_CUCUK', 137, 1.0, 'ELECTRICITY'),
    (3, 'COMP_100HP', 4, 1.0, 'ELECTRICITY'),
    (3, 'COMP_AIKI', 105, 1.0, 'ELECTRICITY'),
    (3, 'COMP_ELITE', 52, 1.0, 'ELECTRICITY'),
    (3, 'COMP_FUSHENG300HP', 51, 1.0, 'ELECTRICITY'),
    (3, 'COMP_INTERLACE', 73, 1.0, 'ELECTRICITY'),
    (3, 'COMP_KAESER', 71, 1.0, 'ELECTRICITY'),
    (3, 'COMP_SCR2200', 98, 1.0, 'ELECTRICITY'),
    (3, 'COMP_WINDER', 72, 1.0, 'ELECTRICITY'),
    (3, 'FACTORY_AB', 84, 1.0, 'ELECTRICITY'),
    (3, 'FINISHING_1', 9, 1.0, 'ELECTRICITY'),
    (3, 'FINISHING_21', 3, 1.0, 'ELECTRICITY'),
    (3, 'FINISHING_22', 5, 1.0, 'ELECTRICITY'),
    (3, 'HEATER_1', 60, 1.0, 'ELECTRICITY'),
    (3, 'HEATER_10', 64, 1.0, 'ELECTRICITY'),
    (3, 'HEATER_11', 59, 1.0, 'ELECTRICITY'),
    (3, 'HEATER_2', 61, 1.0, 'ELECTRICITY'),
    (3, 'HEATER_3', 57, 1.0, 'ELECTRICITY'),
    (3, 'HEATER_4', 58, 1.0, 'ELECTRICITY'),
    (3, 'HEATER_7', 62, 1.0, 'ELECTRICITY'),
    (3, 'HEATER_8', 63, 1.0, 'ELECTRICITY'),
    (3, 'HEATER_TOTAL', 99, 1.0, 'ELECTRICITY'),
    (3, 'HVAC_AHU', 50, 1.0, 'ELECTRICITY'),
    (3, 'HVAC_CHILLER1', 86, 1.0, 'ELECTRICITY'),
    (3, 'HVAC_CHILLER2', 87, 1.0, 'ELECTRICITY'),
    (3, 'INCOMING_PLN', 94, 1.0, 'ELECTRICITY'),
    (3, 'LAB_DEVICE', 16, 1.0, 'ELECTRICITY'),
    (3, 'LIGHTING_MAIN', 48, 1.0, 'ELECTRICITY'),
    (3, 'LVMDB_A1', 23, 1.0, 'ELECTRICITY'),
    (3, 'LVMDB_A2', 24, 1.0, 'ELECTRICITY'),
    (3, 'LVMDB_A3', 25, 1.0, 'ELECTRICITY'),
    (3, 'LVMDB_A4', 26, 1.0, 'ELECTRICITY'),
    (3, 'LVMDB_A5', 28, 1.0, 'ELECTRICITY'),
    (3, 'LVMDB_B2', 12, 1.0, 'ELECTRICITY'),
    (3, 'LVMDB_TEXTURE', 107, 1.0, 'ELECTRICITY'),
    (3, 'LVMDB_TEXTURE_2', 163, 1.0, 'ELECTRICITY'),
    (3, 'LVMDB_TF630', 106, 1.0, 'ELECTRICITY'),
    (3, 'LVMDP_SPINNING_1', 85, 1.0, 'ELECTRICITY'),
    (3, 'LVMDP_SPINNING_2', 90, 1.0, 'ELECTRICITY'),
    (3, 'LVMDP_SPINNING_3', 74, 1.0, 'ELECTRICITY'),
    (3, 'MC302_1_8', 69, 1.0, 'ELECTRICITY'),
    (3, 'MC302_9_22', 102, 1.0, 'ELECTRICITY'),
    (3, 'MC302_BARU', 159, 1.0, 'ELECTRICITY'),
    (3, 'MC303_1_9', 100, 1.0, 'ELECTRICITY'),
    (3, 'MC303_BARU', 158, 1.0, 'ELECTRICITY'),
    (3, 'MC_ATY', 101, 1.0, 'ELECTRICITY'),
    (3, 'MC_MOTOR_1', 37, 1.0, 'ELECTRICITY'),
    (3, 'MC_MOTOR_10', 45, 1.0, 'ELECTRICITY'),
    (3, 'MC_MOTOR_11', 46, 1.0, 'ELECTRICITY'),
    (3, 'MC_MOTOR_12', 56, 1.0, 'ELECTRICITY'),
    (3, 'MC_MOTOR_13', 161, 1.0, 'ELECTRICITY'),
    (3, 'MC_MOTOR_2', 38, 1.0, 'ELECTRICITY'),
    (3, 'MC_MOTOR_3', 103, 1.0, 'ELECTRICITY'),
    (3, 'MC_MOTOR_4', 40, 1.0, 'ELECTRICITY'),
    (3, 'MC_MOTOR_5', 160, 1.0, 'ELECTRICITY'),
    (3, 'MC_MOTOR_7', 43, 1.0, 'ELECTRICITY'),
    (3, 'MC_MOTOR_8', 44, 1.0, 'ELECTRICITY'),
    (3, 'MC_MOTOR_9', 55, 1.0, 'ELECTRICITY'),
    (3, 'MC_SP_D', 79, 1.0, 'ELECTRICITY'),
    (3, 'MC_SP_E', 76, 1.0, 'ELECTRICITY'),
    (3, 'MC_SP_F', 77, 1.0, 'ELECTRICITY'),
    (3, 'MC_SP_G', 78, 1.0, 'ELECTRICITY'),
    (3, 'MC_SP_H', 80, 1.0, 'ELECTRICITY'),
    (3, 'MC_SP_I', 81, 1.0, 'ELECTRICITY'),
    (3, 'MC_SP_J', 82, 1.0, 'ELECTRICITY'),
    (3, 'PACKING_DEVICE', 10, 1.0, 'ELECTRICITY'),
    (3, 'PKN_DEVICE', 17, 1.0, 'ELECTRICITY'),
    (3, 'PLTS_A', 27, 1.0, 'ELECTRICITY'),
    (3, 'PLTS_A4', 167, 1.0, 'ELECTRICITY'),
    (3, 'PLTS_B', 11, 1.0, 'ELECTRICITY'),
    (3, 'PLTS_TEXTURE', 168, 1.0, 'ELECTRICITY'),
    (3, 'RAINCOAT_DEVICE', 6, 1.0, 'ELECTRICITY'),
    (3, 'REWINDING_DEVICE', 54, 1.0, 'ELECTRICITY'),
    (3, 'SIPPA', 138, 1.0, 'ELECTRICITY'),
    (3, 'SIZING', 20, 1.0, 'ELECTRICITY'),
    (3, 'TRICOT', 34, 1.0, 'ELECTRICITY'),
    (3, 'TRICOT1', 35, 1.0, 'ELECTRICITY'),
    (3, 'TRICOT2', 36, 1.0, 'ELECTRICITY'),
    (3, 'WARPING', 21, 1.0, 'ELECTRICITY'),
    (3, 'WJL1', 18, 1.0, 'ELECTRICITY'),
    (3, 'WJL2', 19, 1.0, 'ELECTRICITY'),
    (3, 'WJL3', 33, 1.0, 'ELECTRICITY'),
    (3, 'WJL4', 104, 1.0, 'ELECTRICITY'),
    (3, 'WORKSHOP', 135, 1.0, 'ELECTRICITY'),
    (3, 'WTP_1', 91, 1.0, 'ELECTRICITY'),
    (3, 'WTP_2', 92, 1.0, 'ELECTRICITY'),
    (3, 'WWTP', 139, 1.0, 'ELECTRICITY')
) AS v (tenant_id, node_code, device_id, multiplier, utility_code)
JOIN graph.node n
  ON n.tenant_id = v.tenant_id AND n.node_code = v.node_code
JOIN graph.quantity_rule qr ON qr.utility_code = v.utility_code
ON CONFLICT (node_id, device_id, quantity_id, effective_from)
    WHERE node_id IS NOT NULL DO NOTHING;

-- ----------------------------------------------------------------------
-- Edge-attached measurements (6 device/pipe pairs)
--
-- A flow meter tapped into a pipe measures the PIPE (§4.4). These rows
-- carry edge_id, never node_id -- ck_meas_target enforces exactly one.
-- ----------------------------------------------------------------------
INSERT INTO graph.measurement
    (tenant_id, edge_id, device_id, quantity_id, utility_code, multiplier, role)
SELECT v.tenant_id, e.id, v.device_id, qr.quantity_id, v.utility_code,
       v.multiplier, 'TOTAL'
FROM (VALUES
    (3, 'WTP1_CLR', 'WTP1_SOFT_1', 'WATER', 97, 1.0),
    (3, 'WTP1_RAW', 'WTP1_CLR', 'WATER', 95, 1.0),
    (3, 'WTP2_CLR', 'WTP2_SOFT_3', 'WATER', 164, 1.0),
    (3, 'WTP2_CLR', 'WTP2_SOFT_4', 'WATER', 165, 1.0),
    (3, 'WTP2_CLR', 'WTP2_SOFT_5', 'WATER', 166, 1.0),
    (3, 'WTP2_RAW', 'WTP2_CLR', 'WATER', 96, 1.0)
) AS v (tenant_id, from_code, to_code, utility_code, device_id, multiplier)
JOIN graph.node f ON f.tenant_id = v.tenant_id AND f.node_code = v.from_code
JOIN graph.node t ON t.tenant_id = v.tenant_id AND t.node_code = v.to_code
JOIN graph.edge e ON e.from_node_id = f.id AND e.to_node_id = t.id
                 AND e.utility_code = v.utility_code
JOIN graph.quantity_rule qr ON qr.utility_code = v.utility_code
ON CONFLICT (edge_id, device_id, quantity_id, effective_from)
    WHERE edge_id IS NOT NULL DO NOTHING;

-- ----------------------------------------------------------------------
-- Post-conditions. Any of these raising means the seed did not land whole,
-- and the whole transaction rolls back.
-- ----------------------------------------------------------------------
DO $$
DECLARE v_n INTEGER; v_e INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_n FROM graph.node WHERE tenant_id = 3 AND is_active;
    SELECT COUNT(*) INTO v_e FROM graph.edge WHERE tenant_id = 3 AND is_active;
    IF v_n < 176 THEN
        RAISE EXCEPTION 'tenant 3: expected at least 176 nodes, found %', v_n;
    END IF;
    IF v_e < 231 THEN
        RAISE EXCEPTION 'tenant 3: expected at least 231 edges, found %', v_e;
    END IF;
END $$;

COMMIT;

-- Sanity read-back:
--   SELECT node_class, COUNT(*) FROM graph.node WHERE tenant_id = 3
--    GROUP BY 1 ORDER BY 1;
--   SELECT * FROM graph.v_coverage WHERE tenant_id = 3 AND NOT is_node_metered
--                                    AND NOT is_edge_metered;
